server:
  port: 8082
spring:
  application:
    name: FullStackWebApplication
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fullstackweb?serverTimezone=UTC
    username: 'root'
    password: 'mysqlroot123root'
